import {makeStyles} from '@mui/styles';

export default makeStyles((theme)=>({
    movieContainer:{
        display:'flex',
        flexWrap:'wrap',
        justifyContent:'space-between',
        overflow:'auto',
        [theme.breakpoints.down('sm')]:{
            justifyContent:'center'
        }
       },
   movie:{
    padding:'10px',
   },
   links:{
      alignItems:'center',
      fontWeight:'bolder',
      textDecoration:'none',
      alignItems:'space-between',
      [theme.breakpoints.up('xs')]:{
         display:'flex',
         flexDirection:'column'
      },
      [theme.breakpoints.up('xl')]:{
         display:'flex',
         flexDirection:'column',
      },
      '&:hover':{
         cursor:'pointer'
      },
   },
   image:{
      borderRadius:'20px',
      height:'300px',
      marginBottom:'10px',
      '&:hover':{
        transform:'scale(1.05)',
      }
   },
   title:{
    color:theme.palette.text.primary,
    textOverflow:'ellipsis',
    width:'230px',
    whiteSpace:'nowrap',
    overflow:'hidden',
    marginTop:'10px',
    marginBottom:'0',
    textAllign:'center',
    width:'96%'
   }
}))